parameters:
  build_type: ''
  cmake_flags: ''

steps:
  - bash: |
      brew install cmake ninja pkg-config gtk+3 poppler librsvg adwaita-icon-theme portaudio libsndfile lua libzip cppunit
      export LDFLAGS="-L=/usr/local/opt/libffi/lib"
      export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
    displayName: 'Install dependencies'
  - bash: |
      mkdir build
    displayName: 'Create build directory'
  - bash: |
      cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type}} ${{ parameters.cmake_flags }}
      cmake --build .
    workingDirectory: ./build
    displayName: 'Build Xournal++'