parameters:
  build_type: ''
  cmake_flags: ''

steps:
  - bash: |
      brew update
      brew upgrade
      brew install cmake ninja pkg-config gtk+3 poppler librsvg adwaita-icon-theme portaudio libsndfile lua libzip cppunit
      brew link libffi
    displayName: 'Install dependencies'
  - bash: |
      mkdir build
    displayName: 'Create build directory'
  - bash: |
      cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type}} ${{ parameters.cmake_flags }}
      cmake --build .
    workingDirectory: ./build
    displayName: 'Build Xournal++'