parameters:
  build_type: ''
  cmake_flags: ''

steps:
  - script: |
      pacman --noconfirm -Syuu
      pacman --noconfirm -Syuu
    displayName: 'Update MSYS2'
  - script: |
      bash -lc "mkdir build"
    displayName: 'Create build directory'
  - script: |
      bash -lc "cmake .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type}} ${{ parameters.cmake_flags }}"
      bash -lc "cmake --build ."
    workingDirectory: ./build
    displayName: 'Build Xournal++'
