trigger:
  - master
pr: none

stages:
  - stage: Release
    jobs:
      - job: Windows
        pool:
          vmImage: 'win1803'
        displayName: 'Build Release for Windows'
        containter: xournalpp/xournalpp:latest
        steps:
          - template: steps/build_windows.yml
              parameters:
                build_type: 'Release'
                cmake_flags: ''
          - script: |
              bash -lc "./build-setup.sh"
            workingDirectory: ./windows-setup
            displayName: 'Create Setup'
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: 'windows'
              targetPath: './windows-setup/xournalpp-setup.exe'
            displayName: 'Publish Windows Setup'

      - job: macOS
        pool:
          vmImage: 'macOS-10.13'
        displayName: 'Build for macOS'
        steps:
          - template: steps/build_mac.yml
            parameters:
              build_type: 'Release'
              cmake_flags: ''
#          - bash: |
#              ctest
#            workingDirectory: ./build
#            displayName: 'Run tests'

